In [10]:
import pandas as pd
import numpy as np
df = pd.read_csv("C://titanic/train.csv")
##Df = pd.read_csv("https://github.com/shaliniksh/PortfolioProjects/upload/main/test.csv")
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [21]:
import pandas as pd
import numpy as np
Df2 = pd.read_csv("C://titanic/test.csv")
Df2.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [23]:
Df2

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [11]:
# Let's look at the data
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [12]:
# let's see if there is any missing data
for col in df.columns:
    pct_missing = np.mean(df[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))
    

PassengerId - 0%
Survived - 0%
Pclass - 0%
Name - 0%
Sex - 0%
Age - 20%
SibSp - 0%
Parch - 0%
Ticket - 0%
Fare - 0%
Cabin - 77%
Embarked - 0%


In [13]:
#data types for our columns
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [95]:
#change datatype of columns
df['Age'] = df['Age'].astype('int64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [14]:
df.dropna()

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
10       1   PP 9549  16.7000           G6        S  
11       0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [15]:
# let's examine the data-size
df1 = df.dropna()
print(df1.shape)

(183, 12)


In [16]:
#input
x = df1.iloc[:,[2, 5, 6, 7]].values

#output
y = df1.iloc[:, 2].values

x

array([[ 1.  , 38.  ,  1.  ,  0.  ],
       [ 1.  , 35.  ,  1.  ,  0.  ],
       [ 1.  , 54.  ,  0.  ,  0.  ],
       [ 3.  ,  4.  ,  1.  ,  1.  ],
       [ 1.  , 58.  ,  0.  ,  0.  ],
       [ 2.  , 34.  ,  0.  ,  0.  ],
       [ 1.  , 28.  ,  0.  ,  0.  ],
       [ 1.  , 19.  ,  3.  ,  2.  ],
       [ 1.  , 49.  ,  1.  ,  0.  ],
       [ 1.  , 65.  ,  0.  ,  1.  ],
       [ 1.  , 45.  ,  1.  ,  0.  ],
       [ 2.  , 29.  ,  0.  ,  0.  ],
       [ 3.  , 25.  ,  0.  ,  0.  ],
       [ 1.  , 23.  ,  3.  ,  2.  ],
       [ 1.  , 46.  ,  1.  ,  0.  ],
       [ 1.  , 71.  ,  0.  ,  0.  ],
       [ 1.  , 23.  ,  0.  ,  1.  ],
       [ 1.  , 21.  ,  0.  ,  1.  ],
       [ 1.  , 47.  ,  0.  ,  0.  ],
       [ 1.  , 24.  ,  0.  ,  1.  ],
       [ 2.  , 32.5 ,  0.  ,  0.  ],
       [ 1.  , 54.  ,  0.  ,  1.  ],
       [ 1.  , 19.  ,  0.  ,  2.  ],
       [ 1.  , 37.  ,  1.  ,  0.  ],
       [ 1.  , 24.  ,  0.  ,  0.  ],
       [ 2.  , 36.5 ,  0.  ,  2.  ],
       [ 1.  , 22.  ,  1.  ,  0.  ],
 

In [17]:
#Data spliting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)


In [18]:
# feature scaling
#from sklearn.preprocessing import StandardScaler
#sc_x = StandardScaler()
#xtrain = sc_x.fit_transform(xtrain)
#xtest = sc_x.transform(xtest)
#Print(xtrain[0:50, :])
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scale_data = sc.fit_transform(X_train)
X_train = scale_data
print(X_train)

[[-0.37693562  0.86464248  0.93877253 -0.59844199]
 [-0.37693562  0.92889853  0.93877253 -0.59844199]
 [-0.37693562 -0.74175866 -0.75348848  0.74559986]
 [-0.37693562 -1.32006307 -0.75348848  0.74559986]
 [-0.37693562  0.73613039 -0.75348848 -0.59844199]
 [-0.37693562  0.02931389  0.93877253  2.08964172]
 [-0.37693562 -0.8060147  -0.75348848  0.74559986]
 [-0.37693562 -1.06303889  0.93877253 -0.59844199]
 [ 1.46735653  1.37869085 -0.75348848 -0.59844199]
 [ 1.46735653 -2.02687957  2.63103354  0.74559986]
 [-0.37693562  0.54336226  2.63103354 -0.59844199]
 [-0.37693562  0.6076183  -0.75348848 -0.59844199]
 [-0.37693562 -1.06303889 -0.75348848  2.08964172]
 [-0.37693562  0.67187435 -0.75348848 -0.59844199]
 [-0.37693562  1.82848317  0.93877253  4.77772543]
 [-0.37693562 -0.74175866 -0.75348848 -0.59844199]
 [-0.37693562 -0.74175866 -0.75348848 -0.59844199]
 [-0.37693562  0.80038644 -0.75348848 -0.59844199]
 [-0.37693562 -0.29196634  0.93877253 -0.59844199]
 [-0.37693562  1.63571503 -0.75

In [19]:
import matplotlib.pyplot as plt
from sklearn import preprocessing 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
#classifier = LogisticRegression(solver='lbfgs', random_state=0)
#classifier.fit(X_train, y_train)
# classifier = model.fit(X_train, y_train)
model = LogisticRegression(solver='sag')
clf = model.fit(X_train, y_train)

# Predict class labels on a test data
LR1_pred_labels = model.predict(X_test)

# Print slope and intercept
print('Intercept (Beta 0): ', clf.intercept_)
print('Slope (Beta 1): ', clf.coef_)

Intercept (Beta 0):  [ 3.69677903  0.49176949 -4.18854852]
Slope (Beta 1):  [[-2.71780733  0.30184031  0.17353829  0.00412629]
 [ 0.41375702 -0.06583455  0.03253697 -0.03683348]
 [ 2.30405031 -0.23600576 -0.20607526  0.03270719]]


In [20]:
# Use score method to get accuracy of model
score = model.score(X_test, y_test)
print('Accuracy Score: ', score)
print('--------------------------------------------------------')
# Look at classification report to evaluate the model
print(classification_report(y_test, LR1_pred_labels))

Accuracy Score:  0.8913043478260869
--------------------------------------------------------
              precision    recall  f1-score   support

           1       0.89      1.00      0.94        40
           2       1.00      0.20      0.33         5
           3       0.00      0.00      0.00         1

    accuracy                           0.89        46
   macro avg       0.63      0.40      0.42        46
weighted avg       0.88      0.89      0.85        46



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
